#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                        1
#define TRAINER_SAWYER                      2
#define TRAINER_GRUNT_AQUA_HIDEOUT_1        3
#define TRAINER_GRUNT_AQUA_HIDEOUT_2        4
#define TRAINER_GRUNT_AQUA_HIDEOUT_3        5
#define TRAINER_GRUNT_AQUA_HIDEOUT_4        6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1     7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2     8
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3     9
#define TRAINER_GABRIELLE                   10
#define TRAINER_GRUNT_PETALBURG_WOODS       11
#define TRAINER_MARCEL                      12
#define TRAINER_ALBERTO                     13
#define TRAINER_ED                          14
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4     15
#define TRAINER_DECLAN                      16
#define TRAINER_GRUNT_RUSTURF_TUNNEL        17
#define TRAINER_GRUNT_WEATHER_INST_1        18
#define TRAINER_GRUNT_WEATHER_INST_2        19
#define TRAINER_GRUNT_WEATHER_INST_3        20
#define TRAINER_GRUNT_MUSEUM_1              21
#define TRAINER_GRUNT_MUSEUM_2              22
#define TRAINER_GRUNT_SPACE_CENTER_1        23
#define TRAINER_GRUNT_MT_PYRE_1             24
#define TRAINER_GRUNT_MT_PYRE_2             25
#define TRAINER_GRUNT_MT_PYRE_3             26
#define TRAINER_GRUNT_WEATHER_INST_4        27
#define TRAINER_GRUNT_AQUA_HIDEOUT_5        28
#define TRAINER_GRUNT_AQUA_HIDEOUT_6        29
#define TRAINER_FREDRICK                    30
#define TRAINER_MATT                        31
#define TRAINER_ZANDER                      32
#define TRAINER_SHELLY_WEATHER_INSTITUTE    33
#define TRAINER_SHELLY_SEAFLOOR_CAVERN      34
#define TRAINER_ARCHIE_SEAFLOOR_CAVERN      35
#define TRAINER_LEAH                        36
#define TRAINER_DAISY                       37
#define TRAINER_ROSE                        38
#define TRAINER_FELIX                       39
#define TRAINER_VIOLET                      40
#define TRAINER_DUSTY                       41
#define TRAINER_CHIP                        42
#define TRAINER_FOSTER                      43
#define TRAINER_GABBY_AND_TY_1              44
#define TRAINER_GABBY_AND_TY_2              45
#define TRAINER_GABBY_AND_TY_3              46
#define TRAINER_GABBY_AND_TY_4              47
#define TRAINER_GABBY_AND_TY_5              48
#define TRAINER_GABBY_AND_TY_6              49
#define TRAINER_LOLA                        50
#define TRAINER_AUSTINA                     51
#define TRAINER_GWEN                        52
#define TRAINER_RICKY                       53
#define TRAINER_SIMON                       54
#define TRAINER_CHARLIE                     55
#define TRAINER_RANDALL                     56
#define TRAINER_PARKER                      57
#define TRAINER_GEORGE                      58
#define TRAINER_BERKE                       59
#define TRAINER_BRAXTON                     60
#define TRAINER_VINCENT                     61
#define TRAINER_LEROY                       62
#define TRAINER_WILTON                      63
#define TRAINER_LUKAS                       64
#define TRAINER_MIKE                        65
#define TRAINER_SAMUEL                      66
#define TRAINER_VITO                        67
#define TRAINER_OWEN                        68
#define TRAINER_WARREN                      69
#define TRAINER_MARY                        70
#define TRAINER_ALEXIA                      71
#define TRAINER_JODY                        72
#define TRAINER_WENDY                       73
#define TRAINER_KEIRA                       74
#define TRAINER_BROOKE                      75
#define TRAINER_JENNIFER                    76
#define TRAINER_HOPE                        77
#define TRAINER_SHANNON                     78
#define TRAINER_MICHELLE                    79
#define TRAINER_CAROLINE                    80
#define TRAINER_JULIE                       81
#define TRAINER_PATRICIA                    82
#define TRAINER_KINDRA                      83
#define TRAINER_TAMMY                       84
#define TRAINER_VALERIE                     85
#define TRAINER_TASHA                       86
#define TRAINER_CINDY                       87
#define TRAINER_DAPHNE                      88
#define TRAINER_GRUNT_SPACE_CENTER_2        89
#define TRAINER_BRIANNA                     90
#define TRAINER_NAOMI                       91
#define TRAINER_MELISSA                     92
#define TRAINER_SHEILA                      93
#define TRAINER_SHIRLEY                     94
#define TRAINER_JESSICA                     95
#define TRAINER_CONNIE                      96
#define TRAINER_BRIDGET                     97
#define TRAINER_OLIVIA                      98
#define TRAINER_TIFFANY                     99
#define TRAINER_WINSTON                     100
#define TRAINER_MOLLIE                      101
#define TRAINER_GARRET                      102
#define TRAINER_STEVE                       103
#define TRAINER_THALIA                      104
#define TRAINER_MARK                        105
#define TRAINER_GRUNT_MT_CHIMNEY_1          106
#define TRAINER_LUIS                        107
#define TRAINER_DOMINIK                     108
#define TRAINER_DOUGLAS                     109
#define TRAINER_DARRIN                      110
#define TRAINER_TONY                        111
#define TRAINER_JEROME                      112
#define TRAINER_MATTHEW                     113
#define TRAINER_DAVID                       114
#define TRAINER_SPENCER                     115
#define TRAINER_ROLAND                      116
#define TRAINER_NOLEN                       117
#define TRAINER_STAN                        118
#define TRAINER_BARRY                       119
#define TRAINER_DEAN                        120
#define TRAINER_RODNEY                      121
#define TRAINER_RICHARD                     122
#define TRAINER_HERMAN                      123
#define TRAINER_SANTIAGO                    124
#define TRAINER_GILBERT                     125
#define TRAINER_FRANKLIN                    126
#define TRAINER_KEVIN                       127
#define TRAINER_JACK                        128
#define TRAINER_DUDLEY                      129
#define TRAINER_CHAD                        130
#define TRAINER_TAKAO                       131
#define TRAINER_HITOSHI                     132
#define TRAINER_KIYO                        133
#define TRAINER_KOICHI                      134
#define TRAINER_NOB                         135
#define TRAINER_YUJI                        136
#define TRAINER_DAISUKE                     137
#define TRAINER_ATSUSHI                     138
#define TRAINER_KIRK                        139
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        140
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        141
#define TRAINER_SHAWN                       142
#define TRAINER_FERNANDO                    143
#define TRAINER_DALTON                      144
#define TRAINER_COLE                        145
#define TRAINER_JEFF                        146
#define TRAINER_AXLE                        147
#define TRAINER_JACE                        148
#define TRAINER_KEEGAN                      149
#define TRAINER_BERNIE                      150
#define TRAINER_DREW                        151
#define TRAINER_BEAU                        152
#define TRAINER_LARRY                       153
#define TRAINER_SHANE                       154
#define TRAINER_JUSTIN                      155
#define TRAINER_ETHAN                       156
#define TRAINER_AUTUMN                      157
#define TRAINER_TRAVIS                      158
#define TRAINER_BRENT                       159
#define TRAINER_DONALD                      160
#define TRAINER_TAYLOR                      161
#define TRAINER_JEFFREY                     162
#define TRAINER_DEREK                       163
#define TRAINER_EDWARD                      164
#define TRAINER_PRESTON                     165
#define TRAINER_VIRGIL                      166
#define TRAINER_BLAKE                       167
#define TRAINER_WILLIAM                     168
#define TRAINER_JOSHUA                      169
#define TRAINER_CAMERON                     170
#define TRAINER_JACLYN                      171
#define TRAINER_HANNAH                      172
#define TRAINER_SAMANTHA                    173
#define TRAINER_MAURA                       174
#define TRAINER_KAYLA                       175
#define TRAINER_ALEXIS                      176
#define TRAINER_JACKI                       177
#define TRAINER_WALTER                      178
#define TRAINER_MICAH                       179
#define TRAINER_THOMAS                      180
#define TRAINER_SIDNEY                      181
#define TRAINER_PHOEBE                      182
#define TRAINER_GLACIA                      183
#define TRAINER_DRAKE                       184
#define TRAINER_ROXANNE_1                   185
#define TRAINER_BRAWLY_1                    186
#define TRAINER_WATTSON_1                   187
#define TRAINER_FLANNERY_1                  188
#define TRAINER_NORMAN_1                    189
#define TRAINER_WINONA_1                    190
#define TRAINER_TATE_AND_LIZA_1             191
#define TRAINER_JUAN_1                      192
#define TRAINER_JERRY                       193
#define TRAINER_TED                         194
#define TRAINER_PAUL                        195
#define TRAINER_KAREN                       196
#define TRAINER_GEORGIA                     197
#define TRAINER_KATE_AND_JOY                198
#define TRAINER_ANNA_AND_MEG                199
#define TRAINER_VICTOR                      200
#define TRAINER_MIGUEL                      201
#define TRAINER_COLTON                      202
#define TRAINER_VICTORIA                    203
#define TRAINER_VANESSA                     204
#define TRAINER_BETHANY                     205
#define TRAINER_ISABEL                      206
#define TRAINER_TIMOTHY                     207
#define TRAINER_VICKY                       208
#define TRAINER_SHELBY                      209
#define TRAINER_CALVIN                      210
#define TRAINER_BILLY                       211
#define TRAINER_JOSH                        212
#define TRAINER_TOMMY                       213
#define TRAINER_JOEY                        214
#define TRAINER_BEN                         215
#define TRAINER_QUINCY                      216
#define TRAINER_KATELYNN                    217
#define TRAINER_JAYLEN                      218
#define TRAINER_DILLON                      219
#define TRAINER_EDDIE                       220
#define TRAINER_ALLEN                       221
#define TRAINER_TIMMY                       222
#define TRAINER_WALLACE                     223
#define TRAINER_ANDREW                      224
#define TRAINER_IVAN                        225
#define TRAINER_CLAUDE                      226
#define TRAINER_ELLIOT                      227
#define TRAINER_NED                         228
#define TRAINER_DALE                        229
#define TRAINER_NOLAN                       230
#define TRAINER_BARNY                       231
#define TRAINER_WADE                        232
#define TRAINER_CARTER                      233
#define TRAINER_RONALD                      234
#define TRAINER_JACOB                       235
#define TRAINER_ANTHONY                     236
#define TRAINER_BENJAMIN                    237
#define TRAINER_ABIGAIL                     238
#define TRAINER_JASMINE                     239
#define TRAINER_DYLAN                       240
#define TRAINER_MARIA                       241
#define TRAINER_CAMDEN                      242
#define TRAINER_DEMETRIUS                   243
#define TRAINER_ISAIAH                      244
#define TRAINER_PABLO                       245
#define TRAINER_CHASE                       246
#define TRAINER_ISOBEL                      247
#define TRAINER_DONNY                       248
#define TRAINER_TALIA                       249
#define TRAINER_KATELYN                     250
#define TRAINER_ALLISON                     251
#define TRAINER_NICOLAS                     252
#define TRAINER_AARON                       253
#define TRAINER_PERRY                       254
#define TRAINER_HUGH                        255
#define TRAINER_PHIL                        256
#define TRAINER_JARED                       257
#define TRAINER_HUMBERTO                    258
#define TRAINER_PRESLEY                     259
#define TRAINER_EDWARDO                     260
#define TRAINER_COLIN                       261
#define TRAINER_ROBERT                      262
#define TRAINER_BENNY                       263
#define TRAINER_CHESTER                     264
#define TRAINER_ALEX                        265
#define TRAINER_BECK                        266
#define TRAINER_YASU                        267
#define TRAINER_TAKASHI                     268
#define TRAINER_DIANNE                      269
#define TRAINER_JANI                        270
#define TRAINER_LAO                         271
#define TRAINER_LUNG                        272
#define TRAINER_JOCELYN                     273
#define TRAINER_LAURA                       274
#define TRAINER_CYNDY                       275
#define TRAINER_CORA                        276
#define TRAINER_PAULA                       277
#define TRAINER_MADELINE                    278
#define TRAINER_CLARISSA                    279
#define TRAINER_ANGELICA                    280
#define TRAINER_BEVERLY                     281
#define TRAINER_IMANI                       282
#define TRAINER_KYLA                        283
#define TRAINER_DENISE                      284
#define TRAINER_BETH                        285
#define TRAINER_TARA                        286
#define TRAINER_MISSY                       287
#define TRAINER_ALICE                       288
#define TRAINER_JENNY                       289
#define TRAINER_GRACE                       290
#define TRAINER_TANYA                       291
#define TRAINER_SHARON                      292
#define TRAINER_NIKKI                       293
#define TRAINER_BRENDA                      294
#define TRAINER_KATIE                       295
#define TRAINER_SUSIE                       296
#define TRAINER_KARA                        297
#define TRAINER_DANA                        298
#define TRAINER_SIENNA                      299
#define TRAINER_DEBRA                       300
#define TRAINER_LINDA                       301
#define TRAINER_KAYLEE                      302
#define TRAINER_LAUREL                      303
#define TRAINER_CARLEE                      304
#define TRAINER_HEIDI                       305
#define TRAINER_BECKY                       306
#define TRAINER_CAROL                       307
#define TRAINER_NANCY                       308
#define TRAINER_MARTHA                      309
#define TRAINER_DIANA                       310
#define TRAINER_CEDRIC                      311
#define TRAINER_IRENE                       312
#define TRAINER_AMY_AND_LIV                 313
#define TRAINER_GINA_AND_MIA                314
#define TRAINER_MIU_AND_YUKI                315
#define TRAINER_HUEY                        316
#define TRAINER_EDMOND                      317
#define TRAINER_ERNEST                      318
#define TRAINER_DWAYNE                      319
#define TRAINER_PHILLIP                     320
#define TRAINER_LEONARD                     321
#define TRAINER_DUNCAN                      322
#define TRAINER_ELI                         323
#define TRAINER_ANNIKA                      324
#define TRAINER_JAZMYN                      325
#define TRAINER_JONAS                       326
#define TRAINER_KAYLEY                      327
#define TRAINER_AURON                       328
#define TRAINER_KELVIN                      329
#define TRAINER_MARLEY                      330
#define TRAINER_REYNA                       331
#define TRAINER_HUDSON                      332
#define TRAINER_CONOR                       333
#define TRAINER_EDWIN                       334
#define TRAINER_HECTOR                      335
#define TRAINER_TABITHA_MOSSDEEP            336
#define TRAINER_WALLY_VR                    337
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    338
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    339
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    340
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   341
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   342
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   343
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   344
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   345
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   346
#define TRAINER_MAY_ROUTE_103_MUDKIP        347
#define TRAINER_MAY_ROUTE_110_MUDKIP        348
#define TRAINER_MAY_ROUTE_119_MUDKIP        349
#define TRAINER_MAY_ROUTE_103_TREECKO       350
#define TRAINER_MAY_ROUTE_110_TREECKO       351
#define TRAINER_MAY_ROUTE_119_TREECKO       352
#define TRAINER_MAY_ROUTE_103_TORCHIC       353
#define TRAINER_MAY_ROUTE_110_TORCHIC       354
#define TRAINER_MAY_ROUTE_119_TORCHIC       355
#define TRAINER_ISAAC                       356
#define TRAINER_DAVIS                       357
#define TRAINER_MITCHELL                    358
#define TRAINER_LYDIA                       359
#define TRAINER_HALLE                       360
#define TRAINER_GARRISON                    361
#define TRAINER_JACKSON                     362
#define TRAINER_LORENZO                     363
#define TRAINER_SEBASTIAN                   364
#define TRAINER_CATHERINE                   365
#define TRAINER_JENNA                       366
#define TRAINER_SOPHIA                      367
#define TRAINER_JULIO                       368
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     369
#define TRAINER_GRUNT_MT_PYRE_4             370
#define TRAINER_GRUNT_JAGGED_PASS           371
#define TRAINER_MARC                        372
#define TRAINER_BRENDEN                     373
#define TRAINER_LILITH                      374
#define TRAINER_CRISTIAN                    375
#define TRAINER_SYLVIA                      376
#define TRAINER_LEONARDO                    377
#define TRAINER_ATHENA                      378
#define TRAINER_HARRISON                    379
#define TRAINER_GRUNT_MT_CHIMNEY_2          380
#define TRAINER_CLARENCE                    381
#define TRAINER_TERRY                       382
#define TRAINER_NATE                        383
#define TRAINER_KATHLEEN                    384
#define TRAINER_CLIFFORD                    385
#define TRAINER_NICHOLAS                    386
#define TRAINER_GRUNT_SPACE_CENTER_3        387
#define TRAINER_GRUNT_SPACE_CENTER_4        388
#define TRAINER_GRUNT_SPACE_CENTER_5        389
#define TRAINER_GRUNT_SPACE_CENTER_6        390
#define TRAINER_GRUNT_SPACE_CENTER_7        391
#define TRAINER_MACEY                       392
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    393
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     394
#define TRAINER_PAXTON                      395
#define TRAINER_ISABELLA                    396
#define TRAINER_GRUNT_WEATHER_INST_5        397
#define TRAINER_COURTNEY_MT_CHIMNEY         398
#define TRAINER_JONATHAN                    399
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    400
#define TRAINER_MAY_RUSTBORO_MUDKIP         401
#define TRAINER_MAXIE_MAGMA_HIDEOUT         402
#define TRAINER_MAXIE_MT_CHIMNEY            403
#define TRAINER_TIANA                       404
#define TRAINER_HALEY                       405
#define TRAINER_JANICE                      406
#define TRAINER_VIVI                        407
#define TRAINER_SALLY                       408
#define TRAINER_ROBIN                       409
#define TRAINER_ANDREA                      410
#define TRAINER_CRISSY                      411
#define TRAINER_RICK                        412
#define TRAINER_LYLE                        413
#define TRAINER_JOSE                        414
#define TRAINER_DOUG                        415
#define TRAINER_GREG                        416
#define TRAINER_KENT                        417
#define TRAINER_JAMES                       418
#define TRAINER_BRICE                       419
#define TRAINER_TRENT                       420
#define TRAINER_LENNY                       421
#define TRAINER_LUCAS                       422
#define TRAINER_ALAN                        423
#define TRAINER_CLARK                       424
#define TRAINER_ERIC                        425
#define TRAINER_MIKE_VR                     426
#define TRAINER_DEZ_AND_LUKE                427
#define TRAINER_LEA_AND_JED                 428
#define TRAINER_KIRA_AND_DAN                429
#define TRAINER_JOHANNA                     430
#define TRAINER_GERALD                      431
#define TRAINER_VIVIAN                      432
#define TRAINER_DANIELLE                    433
#define TRAINER_HIDEO                       434
#define TRAINER_KEIGO                       435
#define TRAINER_RILEY                       436
#define TRAINER_FLINT                       437
#define TRAINER_ASHLEY                      438
#define TRAINER_WALLY_MAUVILLE              439
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     440
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    441
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    442
#define TRAINER_MAY_LILYCOVE_MUDKIP         443
#define TRAINER_MAY_LILYCOVE_TREECKO        444
#define TRAINER_MAY_LILYCOVE_TORCHIC        445
#define TRAINER_JONAH                       446
#define TRAINER_HENRY                       447
#define TRAINER_ROGER                       448
#define TRAINER_ALEXA                       449
#define TRAINER_RUBEN                       450
#define TRAINER_KOJI                        451
#define TRAINER_WAYNE                       452
#define TRAINER_AIDAN                       453
#define TRAINER_REED                        454
#define TRAINER_TISHA                       455
#define TRAINER_TORI_AND_TIA                456
#define TRAINER_KIM_AND_IRIS                457
#define TRAINER_TYRA_AND_IVY                458
#define TRAINER_MEL_AND_PAUL                459
#define TRAINER_JOHN_AND_JAY                460
#define TRAINER_RELI_AND_IAN                461
#define TRAINER_LILA_AND_ROY                462
#define TRAINER_LISA_AND_RAY                463
#define TRAINER_CHRIS                       464
#define TRAINER_DAWSON                      465
#define TRAINER_SARAH                       466
#define TRAINER_DARIAN                      467
#define TRAINER_HAILEY                      468
#define TRAINER_CHANDLER                    469
#define TRAINER_KALEB                       470
#define TRAINER_JOSEPH                      471
#define TRAINER_ALYSSA                      472
#define TRAINER_MARCOS                      473
#define TRAINER_RHETT                       474
#define TRAINER_TYRON                       475
#define TRAINER_CELINA                      476
#define TRAINER_BIANCA                      477
#define TRAINER_HAYDEN                      478
#define TRAINER_SOPHIE                      479
#define TRAINER_COBY                        480
#define TRAINER_LAWRENCE                    481
#define TRAINER_WYATT                       482
#define TRAINER_ANGELINA                    483
#define TRAINER_KAI                         484
#define TRAINER_CHARLOTTE                   485
#define TRAINER_DEANDRE                     486
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       487
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       488
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       489
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       490
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       491
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       492
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       493
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       494
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       495
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      496
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      497
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      498
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      499
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      500
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      501
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      502
#define TRAINER_TABITHA_MAGMA_HIDEOUT       503
#define TRAINER_DARCY                       504
#define TRAINER_MAXIE_MOSSDEEP              505
#define TRAINER_PETE                        506
#define TRAINER_ISABELLE                    507
#define TRAINER_ANDRES                      508
#define TRAINER_JOSUE                       509
#define TRAINER_CAMRON                      510
#define TRAINER_CORY                        511
#define TRAINER_CAROLINA                    512
#define TRAINER_ELIJAH                      513
#define TRAINER_CELIA                       514
#define TRAINER_BRYAN                       515
#define TRAINER_BRANDEN                     516
#define TRAINER_BRYANT                      517
#define TRAINER_SHAYLA                      518
#define TRAINER_KYRA                        519
#define TRAINER_JAIDEN                      520
#define TRAINER_ALIX                        521
#define TRAINER_HELENE                      522
#define TRAINER_MARLENE                     523
#define TRAINER_DEVAN                       524
#define TRAINER_JOHNSON                     525
#define TRAINER_MELINA                      526
#define TRAINER_BRANDI                      527
#define TRAINER_AISHA                       528
#define TRAINER_MAKAYLA                     529
#define TRAINER_FABIAN                      530
#define TRAINER_DAYTON                      531
#define TRAINER_RACHEL                      532
#define TRAINER_LEONEL                      533
#define TRAINER_CALLIE                      534
#define TRAINER_CALE                        535
#define TRAINER_MYLES                       536
#define TRAINER_PAT                         537
#define TRAINER_CRISTIN                     538
#define TRAINER_MAY_RUSTBORO_TREECKO        539
#define TRAINER_MAY_RUSTBORO_TORCHIC        540
#define TRAINER_ROXANNE_2                   541
#define TRAINER_BRAWLY_2                    542
#define TRAINER_WATTSON_2                   543
#define TRAINER_FLANNERY_2                  544
#define TRAINER_NORMAN_2                    545
#define TRAINER_WINONA_2                    546
#define TRAINER_TATE_AND_LIZA_2             547
#define TRAINER_JUAN_2                      548
#define TRAINER_ANGELO                      549
#define TRAINER_DARIUS                      550
#define TRAINER_STEVEN                      551
#define TRAINER_ANABEL                      552
#define TRAINER_TUCKER                      553
#define TRAINER_SPENSER                     554
#define TRAINER_GRETA                       555
#define TRAINER_NOLAND                      556
#define TRAINER_LUCY                        557
#define TRAINER_BRANDON                     558
#define TRAINER_MARIELA                     559
#define TRAINER_ALVARO                      560
#define TRAINER_EVERETT                     561
#define TRAINER_RED                         562
#define TRAINER_LEAF                        563
#define TRAINER_BRENDAN_PLACEHOLDER         564
#define TRAINER_MAY_PLACEHOLDER             565
#define TRAINER_AMARA                       566
#define TRAINER_MARIA_SEVII                 567
#define TRAINER_ABIGAIL_SEVII               568
#define TRAINER_FINN                        569
#define TRAINER_GARRETT                     570
#define TRAINER_TOMMY_SEVII                 571
#define TRAINER_SHARON_SEVII                572
#define TRAINER_TANYA_SEVII                 573
#define TRAINER_SHEA                        574
#define TRAINER_HUGH_SEVII                  575
#define TRAINER_BRYCE                       576
#define TRAINER_CLAIRE                      577
#define TRAINER_MIK_AND_KIA                 578
#define TRAINER_GRUNT_MT_EMBER_1            579
#define TRAINER_GRUNT_MT_EMBER_2            580
#define TRAINER_LOGAN                       581
#define TRAINER_BETH_SEVII                  582
#define TRAINER_JOCELYN_SEVII               583
#define TRAINER_GRUNT_MT_EMBER_3            584
#define TRAINER_GRUNT_MT_EMBER_4            585
#define TRAINER_GRUNT_MT_EMBER_5            586
#define TRAINER_GRUNT_MT_EMBER_6            587
#define TRAINER_GRUNT_MT_EMBER_7            588
#define TRAINER_TABITHA_ISLAND_1            589
#define TRAINER_GRUNT_MT_EMBER_8            590
#define TRAINER_GRUNT_MT_EMBER_9            591
#define TRAINER_GRUNT_MT_EMBER_10           592
#define TRAINER_GRUNT_MT_EMBER_11           593
#define TRAINER_COURTNEY_ISLAND_1           594
#define TRAINER_ARCHIE_MUSEUM               595
#define TRAINER_SHELLY_ISLAND_2             596

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      597
#define MAX_TRAINERS_COUNT                  800

#endif  // GUARD_CONSTANTS_OPPONENTS_H
