@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Missed turn$"

gText_LinkStandby4::
	.string "Link standby!$"

gText_WinnerIsPlayersMonCongrats::
	.string "The winner is {Str_Var_1}'s {Str_Var_2}!\n"
	.string "Congratulations!$"

gText_WinnerIsPlayersMon::
	.string "The winner is {Str_Var_1}'s {Str_Var_2}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Primary judging: No. {Str_Var_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Secondary judging: No. {Str_Var_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Set event: No. {Str_Var_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "The move used most often:\n"
	.string "{Str_Var_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "The most impressive Pokémon:\n"
	.string "{Str_Var_1}'s {Str_Var_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Set event: No. {Str_Var_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "A link TV program will not be made\n"
	.string "because the trainer lost.{PAUSE_UNTIL_PRESS}$"
