gContestHallPaintingCaption::
	.string "{Str_Var_1}\n"
	.string "{Str_Var_2}'s {Str_Var_3}$"

@ Unused
gContestPaintingContest::
	.string "Contest$"

gContestRankNormal::
	.string "Normal Rank$"

gContestRankSuper::
	.string "Super Rank$"

gContestRankHyper::
	.string "Hyper Rank$"

gContestRankMaster::
	.string "Master Rank$"

gContestLink::
	.string "Link$"

gContestCoolness::
	.string "Coolness$"

gContestBeauty::
	.string "Beauty$"

gContestCuteness::
	.string "Cuteness$"

gContestSmartness::
	.string "Smartness$"

gContestToughness::
	.string "Toughness$"

gContestPaintingCool1::
	.string "Nonstop supercool--\n"
	.string "the inestimable {Str_Var_1}$"

gContestPaintingCool2::
	.string "Hey, there!\n"
	.string "The good-looking Pokémon {Str_Var_1}$"

gContestPaintingCool3::
	.string "The marvelous, wonderful, and\n"
	.string "very great {Str_Var_1}$"

gContestPaintingBeauty1::
	.string "This century's last Venus--\n"
	.string "the beautiful {Str_Var_1}$"

gContestPaintingBeauty2::
	.string "{Str_Var_1}'s dazzling,\n"
	.string "glittering smile$"

gContestPaintingBeauty3::
	.string "Pokémon Center's super idol--\n"
	.string "the incomparable {Str_Var_1}$"

gContestPaintingCute1::
	.string "The lovely and sweet {Str_Var_1}$"

gContestPaintingCute2::
	.string "The pretty {Str_Var_1}'s\n"
	.string "winning portrait$"

gContestPaintingCute3::
	.string "Give us a wink!\n"
	.string "The cutie Pokémon {Str_Var_1}$"

gContestPaintingSmart1::
	.string "The smartness maestro--\n"
	.string "the wise Pokémon {Str_Var_1}$"

gContestPaintingSmart2::
	.string "{Str_Var_1}--the one chosen\n"
	.string "above all Pokémon$"

gContestPaintingSmart3::
	.string "The excellent {Str_Var_1}'s\n"
	.string "moment of elegance$"

gContestPaintingTough1::
	.string "The powerfully muscular\n"
	.string "speedster {Str_Var_1}$"

gContestPaintingTough2::
	.string "The strong, stronger, and\n"
	.string "strongest {Str_Var_1}$"

gContestPaintingTough3::
	.string "The mighty tough\n"
	.string "hyper Pokémon {Str_Var_1}$"
