gText_ObtainedTheItem::
	.string "Obtained the {Str_Var_2}!$"

gText_TheBagIsFull::
	.string "The bag is full…$"

gText_PutItemInPocket::
	.string "{Player} put away the {Str_Var_2}\n"
	.string "in the {Str_Var_3} pocket.$"

gText_PlayerFoundOneItem::
	.string "{Player} found one {Str_Var_2}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The bag is full…$"

gText_PlayerPutItemInBag::
	.string "{Player} put away the {Str_Var_2}\n"
	.string "in the bag.$"

gText_ObtainedTheDecor::
	.string "Obtained the {Str_Var_2}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {Str_Var_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {Str_Var_2} was transferred\n"
	.string "to the PC.$"
