gText_PkmnTransferredSomeonesPC::
	.string "{Str_Var_2} was transferred to\n"
	.string "Someone's PC.\p"
	.string "It was placed in \n"
	.string "Box “{Str_Var_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{Str_Var_2} was transferred to\n"
	.string "Lanette's PC.\p"
	.string "It was placed in \n"
	.string "Box “{Str_Var_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "Box “{Str_Var_3}” on\n"
	.string "Someone's PC was full.\p"
	.string "{Str_Var_2} was transferred to\n"
	.string "Box “{Str_Var_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "Box “{Str_Var_3}” on\n"
	.string "Lanette's PC was full.\p"
	.string "{Str_Var_2} was transferred to\n"
	.string "Box “{Str_Var_1}.”$"

gText_NoMoreRoomForPokemon::
	.string "There's no more room for Pokémon!\p"
	.string "The Pokémon boxes are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {Str_Var_1}?$"

